export const CATEGORIES = [
  {
    "id": "1",
    "name": "Đồ chơi giáo dục",
    "slug": "giao-duc",
    "image": "https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?w=500&q=80",
    "color": "bg-blue-100/50 hover:bg-blue-200/50 border-blue-200",
    "icon": "🧠"
  },
  {
    "id": "2",
    "name": "LEGO & Lắp ráp",
    "slug": "lego",
    "image": "https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=500&q=80",
    "color": "bg-red-100/50 hover:bg-red-200/50 border-red-200",
    "icon": "🧱"
  },
  {
    "id": "3",
    "name": "Mô hình & Búp bê",
    "slug": "mo-hinh",
    "image": "https://images.unsplash.com/photo-1502086223501-7ea6ecd79368?w=500&q=80",
    "color": "bg-purple-100/50 hover:bg-purple-200/50 border-purple-200",
    "icon": "🦸‍♂️"
  },
  {
    "id": "4",
    "name": "Đồ chơi vận động",
    "slug": "van-dong",
    "image": "https://images.unsplash.com/photo-1555448248-2571daf6344b?w=500&q=80",
    "color": "bg-green-100/50 hover:bg-green-200/50 border-green-200",
    "icon": "🏃‍♂️"
  },
  {
    "id": "5",
    "name": "Đồ chơi nghệ thuật",
    "slug": "nghe-thuat",
    "image": "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=500&q=80",
    "color": "bg-yellow-100/50 hover:bg-yellow-200/50 border-yellow-200",
    "icon": "🎨"
  },
  {
    "id": "6",
    "name": "Gấu bông",
    "slug": "gau-bong",
    "image": "https://images.unsplash.com/photo-1559454403-b8fb88521f11?w=500&q=80",
    "color": "bg-pink-100/50 hover:bg-pink-200/50 border-pink-200",
    "icon": "🧸"
  }
];

export const PRODUCTS = [
  {
    "id": "p1",
    "name": "Bảng chữ cái gỗ thông minh",
    "price": 150000,
    "originalPrice": 180000,
    "image_url": "https://gnukids.vn/uploads/source/hinh-anh-lien-quan/bang-chu-cai-tieng-viet-in-thuong.jpg",
    "rating": 4.8,
    "reviews": 128,
    "category": "Đồ chơi giáo dục",
    "categoryId": "1",
    "brand": "WoodyToys",
    "age": "3-5 tuổi",
    "stock": 50,
    "isNew": true,
    "isSale": true,
    "description": "Bảng chữ cái bằng gỗ cao cấp giúp bé nhận diện mặt chữ, màu sắc và phát triển tư duy logic thông qua việc lắp ghép các khối chữ vào đúng vị trí. Sản phẩm an toàn, sơn không độc hại."
  },
  {
    "id": "p2",
    "name": "LEGO Tàu Vũ Trụ Apollo Siêu Cấp",
    "price": 1200000,
    "originalPrice": 1500000,
    "image_url": "https://muagimuadi.vn/images/products/2025/09/22/large/29(6).webp",
    "rating": 4.9,
    "reviews": 342,
    "category": "LEGO & Lắp ráp",
    "categoryId": "2",
    "brand": "LEGO",
    "age": "8-12 tuổi",
    "stock": 20,
    "isNew": false,
    "isSale": true,
    "description": "Mô hình tàu vũ trụ chi tiết với 500 mảnh ghép, mô phỏng sinh động tàu Apollo. Kích thích trí tưởng tượng, khả năng không không gian và tính kiên nhẫn của bé."
  },
  {
    "id": "p3",
    "name": "Mô hình Siêu Anh Hùng Avenger",
    "price": 850000,
    "originalPrice": 850000,
    "image_url": "https://linhanhkids.com/wp-content/uploads/2019/05/59750170_651761061936332_4816615198930501632_n.jpg",
    "rating": 4.7,
    "reviews": 89,
    "category": "Mô hình & Búp bê",
    "categoryId": "3",
    "brand": "Marvel",
    "age": "Trên 12 tuổi",
    "stock": 15,
    "isNew": true,
    "isSale": false,
    "description": "Mô hình siêu chi tiết với các khớp nối linh hoạt, có đèn LED ở mắt và ngực. Thích hợp cho sưu tầm."
  },
  {
    "id": "p4",
    "name": "Bộ cờ vua quốc tế cao cấp",
    "price": 320000,
    "originalPrice": 350000,
    "image_url": "https://cdn1.fahasa.com/media/catalog/product/8/9/8936146680405_1.jpg",
    "rating": 4.6,
    "reviews": 210,
    "category": "Đồ chơi giáo dục",
    "categoryId": "1",
    "brand": "EduPlay",
    "age": "6-12 tuổi",
    "stock": 100,
    "isNew": false,
    "isSale": true,
    "description": "Bộ cờ vua tiêu chuẩn thi đấu quốc tế, bàn cờ bằng gỗ gấp gọn tiện lợi, quân cờ nam châm hút chặt."
  },
  {
    "id": "p5",
    "name": "Xe điều khiển địa hình RC 4x4",
    "price": 650000,
    "originalPrice": 650000,
    "image_url": "https://media.tripmap.vn/marketplace/2025/09/sieu-xe-dieu-khien-tu-xa-toc-do-cao-20km-h-xe-dua-dia-hinh-1-20-gia-chi-309k-1758038334-600x600.webp",
    "rating": 4.5,
    "reviews": 56,
    "category": "Đồ chơi vận động",
    "categoryId": "4",
    "brand": "SpeedToys",
    "age": "8-12 tuổi",
    "stock": 30,
    "isNew": false,
    "isSale": false,
    "description": "Xe điều khiển từ xa có khả năng vượt địa hình tuyệt vời, bánh xe cao su chống trượt, tốc độ tối đa 25km/h."
  },
  {
    "id": "p6",
    "name": "Bộ đất sét nặn 24 màu",
    "price": 120000,
    "originalPrice": 150000,
    "image_url": "https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-ltysu3z6a0inaf",
    "rating": 4.8,
    "reviews": 412,
    "category": "Đồ chơi nghệ thuật",
    "categoryId": "5",
    "brand": "PlayDoh",
    "age": "3-5 tuổi",
    "stock": 200,
    "isNew": false,
    "isSale": true,
    "description": "Đất sét nặn an toàn, mềm mịn, không dính tay với 24 màu sắc rực rỡ giúp bé thỏa sức sáng tạo nghệ thuật."
  },
  {
    "id": "p7",
    "name": "Gấu Bông Teddy Khổng Lồ",
    "price": 450000,
    "originalPrice": 500000,
    "image_url": "https://image.made-in-china.com/202f0j00cqnohNPEfObt/Customized-Best-Selling-Polychromatic-Kawaii-Lovely-Soft-Giant-Teddy-Bear-Plush-Animal-Toy.webp",
    "rating": 4.9,
    "reviews": 876,
    "category": "Gấu bông",
    "categoryId": "6",
    "brand": "SoftToys",
    "age": "Mọi lứa tuổi",
    "stock": 45,
    "isNew": true,
    "isSale": true,
    "description": "Gấu Teddy cao 1m2 siêu mềm mịn, chất liệu nhồi bông tự nhiên cao cấp không gây dị ứng."
  },
  {
    "id": "p8",
    "name": "Bộ đồ chơi nấu ăn nhà bếp",
    "price": 280000,
    "originalPrice": 280000,
    "image_url": "https://bizweb.dktcdn.net/thumb/grande/100/563/786/products/991b5974-9c8e-41cc-825d-996ea7ad7101.jpg?v=1767944605677",
    "rating": 4.4,
    "reviews": 150,
    "category": "Mô hình & Búp bê",
    "categoryId": "3",
    "brand": "KidsPlay",
    "age": "3-8 tuổi",
    "stock": 60,
    "isNew": false,
    "isSale": false,
    "description": "Bộ đồ chơi mô phỏng nhà bếp với 36 chi tiết bao gồm xoong, nồi, bếp ga có âm thanh và ánh sáng."
  },
  {
    "id": "p9",
    "name": "Bộ Lắp Ráp Khủng Long T-Rex",
    "price": 550000,
    "originalPrice": 650000,
    "image_url": "https://cdn.yeep.vn/2022/03/63190-d6ecbaf12f450d0834301094a91027a153aa5d1d.jpeg",
    "rating": 4.8,
    "reviews": 234,
    "category": "LEGO & Lắp ráp",
    "categoryId": "2",
    "brand": "DinoBlock",
    "age": "8-12 tuổi",
    "stock": 25,
    "isNew": true,
    "isSale": true,
    "description": "Mô hình khủng long T-Rex khổng lồ sau khi lắp ráp có thể cử động hàm và đuôi. Gồm 650 mảnh ghép."
  },
  {
    "id": "p10",
    "name": "Đồ chơi Rubik 3x3 Tốc Độ Cao",
    "price": 85000,
    "originalPrice": 100000,
    "image_url": "https://bizweb.dktcdn.net/thumb/1024x1024/100/403/846/products/42-b4914c9c-e668-4cb3-a5c9-e03279daaf2d.jpg?v=1762678954063",
    "rating": 4.9,
    "reviews": 1205,
    "category": "Đồ chơi giáo dục",
    "categoryId": "1",
    "brand": "GanCube",
    "age": "Từ 6 tuổi",
    "stock": 150,
    "isNew": false,
    "isSale": true,
    "description": "Khối Rubik xoay cực êm, chống kẹt, giúp phát triển trí não và khả năng tư duy logic nhanh nhạy."
  },
  {
    "id": "p11",
    "name": "Bộ Vẽ Tranh Sáng Tạo 150 Chi Tiết",
    "price": 250000,
    "originalPrice": 250000,
    "image_url": "https://www.tiktok.com/api/img/?itemId=7249716492814667013&location=0&aid=1988",
    "rating": 4.6,
    "reviews": 310,
    "category": "Đồ chơi nghệ thuật",
    "categoryId": "5",
    "brand": "ArtKids",
    "age": "4-10 tuổi",
    "stock": 80,
    "isNew": false,
    "isSale": false,
    "description": "Hộp màu 150 chi tiết bao gồm sáp màu, màu nước, cọ vẽ... Món quà tuyệt vời cho các họa sĩ nhí."
  },
  {
    "id": "p12",
    "name": "Thỏ Bông Tai Dài Đáng Yêu",
    "price": 180000,
    "originalPrice": 220000,
    "image_url": "https://giadinhgaubong.vn/upload/elfinder/7E33D552-32FD-4DA8-93D6-44FB97D7AE29-3.jpeg",
    "rating": 4.8,
    "reviews": 420,
    "category": "Gấu bông",
    "categoryId": "6",
    "brand": "SoftToys",
    "age": "Mọi lứa tuổi",
    "stock": 55,
    "isNew": true,
    "isSale": true,
    "description": "Thỏ bông mềm mại, tai dài dễ thương, là người bạn đồng hành tuyệt vời cho bé vào giấc ngủ."
  },
  {
    "id": "p13",
    "name": "Bộ Lắp Ráp Xe Đua F1",
    "price": 450000,
    "originalPrice": 500000,
    "image_url": "https://down-vn.img.susercontent.com/file/vn-11134207-820l4-mesml29slf5sc8",
    "rating": 4.7,
    "reviews": 156,
    "category": "LEGO & Lắp ráp",
    "categoryId": "2",
    "brand": "SpeedBlock",
    "age": "8-12 tuổi",
    "stock": 40,
    "isNew": true,
    "isSale": true,
    "description": "Mô hình xe đua F1 siêu tốc độ với hơn 400 chi tiết, giúp rèn luyện tính kiên nhẫn và sự khéo léo."
  },
  {
    "id": "p14",
    "name": "Cầu Trượt Mini Trong Nhà",
    "price": 1550000,
    "originalPrice": 1550000,
    "image_url": "https://sudospaces.com/babycuatoi/2020/07/zk1056-cau-truot-nha-choi-lien-hoan-cho-be-2.jpg",
    "rating": 4.9,
    "reviews": 89,
    "category": "Đồ chơi vận động",
    "categoryId": "4",
    "brand": "ActiveKids",
    "age": "2-5 tuổi",
    "stock": 15,
    "isNew": false,
    "isSale": false,
    "description": "Cầu trượt nhựa nguyên sinh an toàn, màu sắc bắt mắt, phù hợp không gian phòng khách hoặc phòng ngủ của bé."
  },
  {
    "id": "p15",
    "name": "Búp Bê Công Chúa Elsa",
    "price": 350000,
    "originalPrice": 400000,
    "image_url": "https://linhanhkids.com/wp-content/uploads/2017/09/bup-be-cong-chua-elsa-kitchen-set-2.jpg",
    "rating": 4.8,
    "reviews": 520,
    "category": "Mô hình & Búp bê",
    "categoryId": "3",
    "brand": "Disney",
    "age": "3-8 tuổi",
    "stock": 60,
    "isNew": false,
    "isSale": true,
    "description": "Búp bê Elsa xinh đẹp với bộ váy lấp lánh có thể phát nhạc bài hát Let It Go."
  },
  {
    "id": "p16",
    "name": "Đàn Piano Mini Cho Bé",
    "price": 680000,
    "originalPrice": 750000,
    "image_url": "https://img.lazcdn.com/g/shop/bfb9f2d85e4a15e55df0659e6c02adf1.png_960x960q80.png_.webp",
    "rating": 4.6,
    "reviews": 215,
    "category": "Đồ chơi nghệ thuật",
    "categoryId": "5",
    "brand": "MusicStar",
    "age": "3-7 tuổi",
    "stock": 25,
    "isNew": true,
    "isSale": true,
    "description": "Đàn piano 37 phím với âm thanh trung thực, kèm theo micro cho bé thỏa sức ca hát."
  },
  {
    "id": "p17",
    "name": "Lều Cắm Trại Trẻ Em",
    "price": 290000,
    "originalPrice": 290000,
    "image_url": "https://phukiengiagoc.vn/wp-content/uploads/2022/06/eZy-Watermark_27-06-2022_09-33-53AM.jpg",
    "rating": 4.5,
    "reviews": 134,
    "category": "Đồ chơi vận động",
    "categoryId": "4",
    "brand": "CampKids",
    "age": "3-10 tuổi",
    "stock": 45,
    "isNew": false,
    "isSale": false,
    "description": "Lều vải canvas phong cách Hàn Quốc cực kỳ đáng yêu, là góc vui chơi bí mật hoàn hảo cho trẻ."
  },
  {
    "id": "p18",
    "name": "Bộ Thẻ Flashcard Tiếng Anh",
    "price": 120000,
    "originalPrice": 150000,
    "image_url": "https://linhanhkids.com/wp-content/uploads/2021/12/b491e4be5c5a9704ce4b.jpg",
    "rating": 4.9,
    "reviews": 672,
    "category": "Đồ chơi giáo dục",
    "categoryId": "1",
    "brand": "BrainyBaby",
    "age": "1-4 tuổi",
    "stock": 120,
    "isNew": false,
    "isSale": true,
    "description": "100 thẻ học từ vựng tiếng Anh với hình ảnh minh họa sinh động, chất liệu giấy cứng chống thấm nước."
  },
  {
    "id": "p19",
    "name": "Cá Heo Nhồi Bông",
    "price": 220000,
    "originalPrice": 250000,
    "image_url": "https://api.dybiweb.com/Files/9465bac2-0aa8-43e4-8e48-cc3c1388bbe5/Item/Moc-khoa-ca-heo-nhoi-bong-nhieu-mau_4_92173-197370fa-1d64-492a-ac83-ead1fb8b9731.jpg",
    "rating": 4.7,
    "reviews": 189,
    "category": "Gấu bông",
    "categoryId": "6",
    "brand": "SoftToys",
    "age": "Mọi lứa tuổi",
    "stock": 70,
    "isNew": true,
    "isSale": true,
    "description": "Cá heo xanh nhồi bông cực kỳ êm ái, thích hợp làm gối ôm mang lại giấc ngủ ngon."
  },
  {
    "id": "p20",
    "name": "Xe Trượt Scooter 3 Bánh Có Đèn",
    "price": 550000,
    "originalPrice": 650000,
    "image_url": "https://i.ytimg.com/vi/jvfIis9zApk/hqdefault.jpg?sqp=-oaymwEmCOADEOgC8quKqQMa8AEB-AH-CYAC0AWKAgwIABABGD0gYShyMA8=&rs=AOn4CLCH_eyG45i92tbuCbMzT3wQYl074A",
    "rating": 4.8,
    "reviews": 312,
    "category": "Đồ chơi vận động",
    "categoryId": "4",
    "brand": "ActiveKids",
    "age": "4-8 tuổi",
    "stock": 55,
    "isNew": false,
    "isSale": true,
    "description": "Xe trượt scooter khung thép chắc chắn, bánh xe có đèn LED phát sáng cực đẹp khi di chuyển."
  },
  {
    "id": "p21",
    "name": "Bộ giáo Khổng Lồ 21",
    "price": 225000,
    "originalPrice": 250000,
    "image_url": "https://www.tiktok.com/api/img/?itemId=7582922963448630536&location=0&aid=1988",
    "rating": "4.0",
    "reviews": 121,
    "category": "Đồ chơi giáo dục",
    "categoryId": "1",
    "brand": "ToyBrands",
    "age": "3-5 tuổi",
    "stock": 41,
    "isNew": true,
    "isSale": true,
    "description": "Sản phẩm Bộ giáo Khổng Lồ 21 mang lại niềm vui bất tận cho bé. Thiết kế an toàn, chất liệu cao cấp."
  },
  {
    "id": "p22",
    "name": "Khối & Siêu Cấp 22",
    "price": 420000,
    "originalPrice": 600000,
    "image_url": "https://img.tgdd.vn/imgt/ecom/f_webp,fit_outside,quality_95/https://cdn.tgdd.vn/Products/Images/10421/329797/do-choi-dap-bong-lan-huanger-3lhe0290-thumb-600x600.jpg",
    "rating": "4.4",
    "reviews": 236,
    "category": "Mô hình & Búp bê",
    "categoryId": "3",
    "brand": "ToyBrands",
    "age": "Trên 12 tuổi",
    "stock": 84,
    "isNew": true,
    "isSale": true,
    "description": "Sản phẩm Khối & Siêu Cấp 22 mang lại niềm vui bất tận cho bé. Thiết kế an toàn, chất liệu cao cấp."
  },
  {
    "id": "p23",
    "name": "Đồ chơi vận Đa Năng 23",
    "price": 720000,
    "originalPrice": 900000,
    "image_url": "https://static.vinwonders.com/production/tro-choi-dan-gian-2.jpg",
    "rating": "4.7",
    "reviews": 31,
    "category": "Đồ chơi vận động",
    "categoryId": "4",
    "brand": "ToyBrands",
    "age": "3-5 tuổi",
    "stock": 50,
    "isNew": false,
    "isSale": true,
    "description": "Sản phẩm Đồ chơi vận Đa Năng 23 mang lại niềm vui bất tận cho bé. Thiết kế an toàn, chất liệu cao cấp."
  },
  {
    "id": "p24",
    "name": "Gấu nghệ Phát Sáng 24",
    "price": 585000,
    "originalPrice": 650000,
    "image_url": "https://cdn-v2.kidsplaza.vn/media/wysiwyg/product/dochoi/do-choi-am-thanh/do-choi-dan-hinh-gau-cy-776-1.jpg?fm=webp&q=75&w=320",
    "rating": "4.4",
    "reviews": 111,
    "category": "Đồ chơi nghệ thuật",
    "categoryId": "5",
    "brand": "ToyBrands",
    "age": "4-7 tuổi",
    "stock": 80,
    "isNew": true,
    "isSale": true,
    "description": "Sản phẩm Gấu nghệ Phát Sáng 24 mang lại niềm vui bất tận cho bé. Thiết kế an toàn, chất liệu cao cấp."
  },
  {
    "id": "p25",
    "name": "Khối vận Phát Sáng 25",
    "price": 900000,
    "originalPrice": 900000,
    "image_url": "https://i.ytimg.com/vi/vKW-s5rNJvU/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLDPCCqHaAYkAixhfIMjIZuXVVfWFA",
    "rating": "4.4",
    "reviews": 489,
    "category": "Đồ chơi vận động",
    "categoryId": "4",
    "brand": "ToyBrands",
    "age": "0-3 tuổi",
    "stock": 80,
    "isNew": false,
    "isSale": false,
    "description": "Sản phẩm Khối vận Phát Sáng 25 mang lại niềm vui bất tận cho bé. Thiết kế an toàn, chất liệu cao cấp."
  },
  {
    "id": "p26",
    "name": "Bộ cờ nghệ Sáng Tạo 26",
    "price": 630000,
    "originalPrice": 900000,
    "image_url": "https://toplist.vn/images/800px/gian-hang-am-thuc-1063205.jpg",
    "rating": "4.3",
    "reviews": 404,
    "category": "Đồ chơi nghệ thuật",
    "categoryId": "5",
    "brand": "ToyBrands",
    "age": "6-12 tuổi",
    "stock": 13,
    "isNew": true,
    "isSale": true,
    "description": "Sản phẩm Bộ cờ nghệ Sáng Tạo 26 mang lại niềm vui bất tận cho bé. Thiết kế an toàn, chất liệu cao cấp."
  },
  {
    "id": "p27",
    "name": "Bộ cờ Đồ chơi Sáng Tạo 27",
    "price": 315000,
    "originalPrice": 450000,
    "image_url": "https://bizweb.dktcdn.net/100/453/361/products/3-1.jpg?v=1691557051793",
    "rating": "4.4",
    "reviews": 182,
    "category": "Gấu bông",
    "categoryId": "6",
    "brand": "ToyBrands",
    "age": "Trên 12 tuổi",
    "stock": 38,
    "isNew": true,
    "isSale": true,
    "description": "Sản phẩm Bộ cờ Đồ chơi Sáng Tạo 27 mang lại niềm vui bất tận cho bé. Thiết kế an toàn, chất liệu cao cấp."
  },
  {
    "id": "p28",
    "name": "Lều & Thông Minh 28",
    "price": 850000,
    "originalPrice": 850000,
    "image_url": "https://product.hstatic.net/1000217316/product/307996727_616885276568675_160132721186872497_n_5525ce363ab34ac288325f5c6ac59052_large.jpg",
    "rating": "4.2",
    "reviews": 286,
    "category": "Mô hình & Búp bê",
    "categoryId": "3",
    "brand": "ToyBrands",
    "age": "Mọi lứa tuổi",
    "stock": 20,
    "isNew": false,
    "isSale": false,
    "description": "Sản phẩm Lều & Thông Minh 28 mang lại niềm vui bất tận cho bé. Thiết kế an toàn, chất liệu cao cấp."
  },
  {
    "id": "p29",
    "name": "Khối Lắp Cao Cấp 29",
    "price": 270000,
    "originalPrice": 300000,
    "image_url": "https://pakey.vn/wp-content/uploads/2025/09/xe-do-choi-1.jpg",
    "rating": "4.3",
    "reviews": 498,
    "category": "LEGO & Lắp ráp",
    "categoryId": "2",
    "brand": "ToyBrands",
    "age": "3-5 tuổi",
    "stock": 62,
    "isNew": false,
    "isSale": true,
    "description": "Sản phẩm Khối Lắp Cao Cấp 29 mang lại niềm vui bất tận cho bé. Thiết kế an toàn, chất liệu cao cấp."
  },
  {
    "id": "p30",
    "name": "Mô hình nghệ Thông Minh 30",
    "price": 750000,
    "originalPrice": 750000,
    "image_url": "https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lvlv25m2b0v1da",
    "rating": "4.2",
    "reviews": 276,
    "category": "Đồ chơi nghệ thuật",
    "categoryId": "5",
    "brand": "ToyBrands",
    "age": "6-12 tuổi",
    "stock": 76,
    "isNew": true,
    "isSale": false,
    "description": "Sản phẩm Mô hình nghệ Thông Minh 30 mang lại niềm vui bất tận cho bé. Thiết kế an toàn, chất liệu cao cấp."
  },
  {
    "id": "p31",
    "name": "Thú nhồi bông vận Sáng Tạo 31",
    "price": 270000,
    "originalPrice": 300000,
    "image_url": "https://dochoihoangthu.com/wp-content/uploads/2025/08/giot-nuoc-nhoi-bong-7.png",
    "rating": "4.1",
    "reviews": 90,
    "category": "Đồ chơi vận động",
    "categoryId": "4",
    "brand": "ToyBrands",
    "age": "8-12 tuổi",
    "stock": 89,
    "isNew": true,
    "isSale": true,
    "description": "Sản phẩm Thú nhồi bông vận Sáng Tạo 31 mang lại niềm vui bất tận cho bé. Thiết kế an toàn, chất liệu cao cấp."
  },
  {
    "id": "p32",
    "name": "Bộ cờ & Đa Năng 32",
    "price": 450000,
    "originalPrice": 450000,
    "image_url": "https://bizweb.dktcdn.net/100/182/839/products/do-choi-cau-ca-nam-cham-3d-bang-go-32-con.jpg?v=1630912705803",
    "rating": "4.8",
    "reviews": 113,
    "category": "Mô hình & Búp bê",
    "categoryId": "3",
    "brand": "ToyBrands",
    "age": "4-7 tuổi",
    "stock": 27,
    "isNew": true,
    "isSale": false,
    "description": "Sản phẩm Bộ cờ & Đa Năng 32 mang lại niềm vui bất tận cho bé. Thiết kế an toàn, chất liệu cao cấp."
  },
  {
    "id": "p33",
    "name": "Bộ cờ vận Phát Sáng 33",
    "price": 750000,
    "originalPrice": 750000,
    "image_url": "https://cdn1.fahasa.com/media/catalog/product/8/9/8938548313097-_6_.jpg",
    "rating": "4.7",
    "reviews": 234,
    "category": "Đồ chơi vận động",
    "categoryId": "4",
    "brand": "ToyBrands",
    "age": "6-12 tuổi",
    "stock": 76,
    "isNew": true,
    "isSale": false,
    "description": "Sản phẩm Bộ cờ vận Phát Sáng 33 mang lại niềm vui bất tận cho bé. Thiết kế an toàn, chất liệu cao cấp."
  },
  {
    "id": "p34",
    "name": "Bộ vận Mini 34",
    "price": 400000,
    "originalPrice": 400000,
    "image_url": "https://mediacdn1.bibomart.net/images/2025/12/17/0/origin/xe-dien-cho-be-117122025071905.jpg",
    "rating": "4.5",
    "reviews": 464,
    "category": "Đồ chơi vận động",
    "categoryId": "4",
    "brand": "ToyBrands",
    "age": "6-12 tuổi",
    "stock": 54,
    "isNew": true,
    "isSale": false,
    "description": "Sản phẩm Bộ vận Mini 34 mang lại niềm vui bất tận cho bé. Thiết kế an toàn, chất liệu cao cấp."
  },
  {
    "id": "p35",
    "name": "Đồ chơi giáo Đa Năng 35",
    "price": 525000,
    "originalPrice": 750000,
    "image_url": "https://bizweb.dktcdn.net/thumb/1024x1024/100/403/846/products/122785937-141424654335847-8051840577480105393-n.jpg?v=1603953067253",
    "rating": "4.5",
    "reviews": 413,
    "category": "Đồ chơi giáo dục",
    "categoryId": "1",
    "brand": "ToyBrands",
    "age": "Trên 12 tuổi",
    "stock": 65,
    "isNew": false,
    "isSale": true,
    "description": "Sản phẩm Đồ chơi giáo Đa Năng 35 mang lại niềm vui bất tận cho bé. Thiết kế an toàn, chất liệu cao cấp."
  },
  {
    "id": "p36",
    "name": "Mô hình nghệ Siêu Cấp 36",
    "price": 600000,
    "originalPrice": 600000,
    "image_url": "https://cdn1.fahasa.com/media/catalog/product/4/7/4716503206912.jpg",
    "rating": "4.6",
    "reviews": 106,
    "category": "Đồ chơi nghệ thuật",
    "categoryId": "5",
    "brand": "ToyBrands",
    "age": "Trên 12 tuổi",
    "stock": 106,
    "isNew": false,
    "isSale": false,
    "description": "Sản phẩm Mô hình nghệ Siêu Cấp 36 mang lại niềm vui bất tận cho bé. Thiết kế an toàn, chất liệu cao cấp."
  },
  {
    "id": "p37",
    "name": "Đồ chơi nghệ Cao Cấp 37",
    "price": 600000,
    "originalPrice": 600000,
    "image_url": "https://www.tiktok.com/api/img/?itemId=7636750441803418901&location=0&aid=1988",
    "rating": "4.6",
    "reviews": 476,
    "category": "Đồ chơi nghệ thuật",
    "categoryId": "5",
    "brand": "ToyBrands",
    "age": "Mọi lứa tuổi",
    "stock": 45,
    "isNew": false,
    "isSale": false,
    "description": "Sản phẩm Đồ chơi nghệ Cao Cấp 37 mang lại niềm vui bất tận cho bé. Thiết kế an toàn, chất liệu cao cấp."
  },
  {
    "id": "p38",
    "name": "Bộ & Phát Sáng 38",
    "price": 850000,
    "originalPrice": 850000,
    "image_url": "https://www.tiktok.com/api/img/?itemId=7435067683525152007&location=0&aid=1988",
    "rating": "4.9",
    "reviews": 273,
    "category": "Mô hình & Búp bê",
    "categoryId": "3",
    "brand": "ToyBrands",
    "age": "Trên 12 tuổi",
    "stock": 51,
    "isNew": false,
    "isSale": false,
    "description": "Sản phẩm Bộ & Phát Sáng 38 mang lại niềm vui bất tận cho bé. Thiết kế an toàn, chất liệu cao cấp."
  },
  {
    "id": "p39",
    "name": "Thú nhồi bông giáo Cao Cấp 39",
    "price": 350000,
    "originalPrice": 350000,
    "image_url": "https://cdn.vuahanghieu.com/unsafe/0x900/left/top/smart/filters:quality(90)/https://admin.vuahanghieu.com/upload/product/2024/07/moc-khoa-gau-bong-toyzeroplus-teddy-lulu-the-piggy-mau-vang-668deea576ac6-10072024091501.jpg",
    "rating": "4.6",
    "reviews": 423,
    "category": "Đồ chơi giáo dục",
    "categoryId": "1",
    "brand": "ToyBrands",
    "age": "Mọi lứa tuổi",
    "stock": 97,
    "isNew": false,
    "isSale": false,
    "description": "Sản phẩm Thú nhồi bông giáo Cao Cấp 39 mang lại niềm vui bất tận cho bé. Thiết kế an toàn, chất liệu cao cấp."
  },
  {
    "id": "p40",
    "name": "Xe Lắp Mini 40",
    "price": 560000,
    "originalPrice": 700000,
    "image_url": "https://product.hstatic.net/1000320222/product/upload_756eed6df2ee461f84d97bdffafbc008_large.jpg",
    "rating": "4.2",
    "reviews": 22,
    "category": "LEGO & Lắp ráp",
    "categoryId": "2",
    "brand": "ToyBrands",
    "age": "Trên 12 tuổi",
    "stock": 39,
    "isNew": true,
    "isSale": true,
    "description": "Sản phẩm Xe Lắp Mini 40 mang lại niềm vui bất tận cho bé. Thiết kế an toàn, chất liệu cao cấp."
  },
  {
    "id": "p41",
    "name": "Bộ cờ Đồ chơi Thông Minh 41",
    "price": 350000,
    "originalPrice": 500000,
    "image_url": "https://down-vn.img.susercontent.com/file/ca89897e8cfddd5fa01e22c35e142359",
    "rating": "4.1",
    "reviews": 315,
    "category": "Gấu bông",
    "categoryId": "6",
    "brand": "ToyBrands",
    "age": "8-12 tuổi",
    "stock": 25,
    "isNew": true,
    "isSale": true,
    "description": "Sản phẩm Bộ cờ Đồ chơi Thông Minh 41 mang lại niềm vui bất tận cho bé. Thiết kế an toàn, chất liệu cao cấp."
  },
  {
    "id": "p42",
    "name": "Bộ cờ Đồ chơi Khổng Lồ 42",
    "price": 600000,
    "originalPrice": 750000,
    "image_url": "https://baongonstore.com/watermark/product/1000x0x2/upload/product/3914967814600780947-2-6137.jpg",
    "rating": "4.7",
    "reviews": 441,
    "category": "Gấu bông",
    "categoryId": "6",
    "brand": "ToyBrands",
    "age": "3-5 tuổi",
    "stock": 100,
    "isNew": false,
    "isSale": true,
    "description": "Sản phẩm Bộ cờ Đồ chơi Khổng Lồ 42 mang lại niềm vui bất tận cho bé. Thiết kế an toàn, chất liệu cao cấp."
  },
  {
    "id": "p43",
    "name": "Lều giáo Siêu Cấp 43",
    "price": 675000,
    "originalPrice": 750000,
    "image_url": "https://www.tiktok.com/api/img/?itemId=7539455453797862664&location=0&aid=1988",
    "rating": "4.1",
    "reviews": 441,
    "category": "Đồ chơi giáo dục",
    "categoryId": "1",
    "brand": "ToyBrands",
    "age": "8-12 tuổi",
    "stock": 18,
    "isNew": true,
    "isSale": true,
    "description": "Sản phẩm Lều giáo Siêu Cấp 43 mang lại niềm vui bất tận cho bé. Thiết kế an toàn, chất liệu cao cấp."
  },
  {
    "id": "p44",
    "name": "Đàn vận Phát Sáng 44",
    "price": 630000,
    "originalPrice": 900000,
    "image_url": "https://cdn.tgdd.vn//News/1472547//top-10-mau-do-choi-sang-tao-cho-tre-mam-non-giup-7-845x500.jpg",
    "rating": "4.0",
    "reviews": 127,
    "category": "Đồ chơi vận động",
    "categoryId": "4",
    "brand": "ToyBrands",
    "age": "3-5 tuổi",
    "stock": 19,
    "isNew": true,
    "isSale": true,
    "description": "Sản phẩm Đàn vận Phát Sáng 44 mang lại niềm vui bất tận cho bé. Thiết kế an toàn, chất liệu cao cấp."
  },
  {
    "id": "p45",
    "name": "Đàn giáo Cao Cấp 45",
    "price": 520000,
    "originalPrice": 650000,
    "image_url": "https://down-vn.img.susercontent.com/file/sg-11134201-8262j-mmbdavvhcpagbf",
    "rating": "4.8",
    "reviews": 257,
    "category": "Đồ chơi giáo dục",
    "categoryId": "1",
    "brand": "ToyBrands",
    "age": "3-5 tuổi",
    "stock": 103,
    "isNew": true,
    "isSale": true,
    "description": "Sản phẩm Đàn giáo Cao Cấp 45 mang lại niềm vui bất tận cho bé. Thiết kế an toàn, chất liệu cao cấp."
  },
  {
    "id": "p46",
    "name": "Bộ cờ Đồ chơi Mini 46",
    "price": 225000,
    "originalPrice": 250000,
    "image_url": "https://cdn1.fahasa.com/media/catalog/product/8/9/8938548313097-_2_.jpg",
    "rating": "4.8",
    "reviews": 258,
    "category": "Gấu bông",
    "categoryId": "6",
    "brand": "ToyBrands",
    "age": "3-5 tuổi",
    "stock": 39,
    "isNew": false,
    "isSale": true,
    "description": "Sản phẩm Bộ cờ Đồ chơi Mini 46 mang lại niềm vui bất tận cho bé. Thiết kế an toàn, chất liệu cao cấp."
  },
  {
    "id": "p47",
    "name": "Gấu & Phát Sáng 47",
    "price": 210000,
    "originalPrice": 300000,
    "image_url": "https://image.made-in-china.com/202f0j00iogqrDKICwbY/Gachapon-Gacha-Vending-Machine-Cute-Bear-Capsule-Toy-Machine-Gift-Vending-Equipment.webp",
    "rating": "4.4",
    "reviews": 208,
    "category": "Mô hình & Búp bê",
    "categoryId": "3",
    "brand": "ToyBrands",
    "age": "3-5 tuổi",
    "stock": 15,
    "isNew": false,
    "isSale": true,
    "description": "Sản phẩm Gấu & Phát Sáng 47 mang lại niềm vui bất tận cho bé. Thiết kế an toàn, chất liệu cao cấp."
  },
  {
    "id": "p48",
    "name": "Bộ cờ Lắp Thông Minh 48",
    "price": 750000,
    "originalPrice": 750000,
    "image_url": "https://www.mykingdom.com.vn/cdn/shop/files/PAB048_16d400e6-7d6f-4ffa-a76c-ae4859751e02.jpg?v=1776398402",
    "rating": "4.3",
    "reviews": 183,
    "category": "LEGO & Lắp ráp",
    "categoryId": "2",
    "brand": "ToyBrands",
    "age": "3-5 tuổi",
    "stock": 13,
    "isNew": true,
    "isSale": false,
    "description": "Sản phẩm Bộ cờ Lắp Thông Minh 48 mang lại niềm vui bất tận cho bé. Thiết kế an toàn, chất liệu cao cấp."
  },
  {
    "id": "p49",
    "name": "Đàn nghệ Đa Năng 49",
    "price": 700000,
    "originalPrice": 700000,
    "image_url": "https://cdnmedia.baotintuc.vn/Upload/c2tvplmdloSDblsn03qN2Q/files/2026/05/12/chinh-quyen-nguoi-dan-moi-truong-so.jpg",
    "rating": "4.0",
    "reviews": 377,
    "category": "Đồ chơi nghệ thuật",
    "categoryId": "5",
    "brand": "ToyBrands",
    "age": "3-5 tuổi",
    "stock": 73,
    "isNew": true,
    "isSale": false,
    "description": "Sản phẩm Đàn nghệ Đa Năng 49 mang lại niềm vui bất tận cho bé. Thiết kế an toàn, chất liệu cao cấp."
  },
  {
    "id": "p50",
    "name": "Thú nhồi bông Lắp Đáng Yêu 50",
    "price": 500000,
    "originalPrice": 500000,
    "image_url": "https://cdn.hstatic.net/products/200000122283/z6923038566428_754f5f9421a5277173646b173b9375b2_f17f5e4a96f34775bfb97861ac0e5979_grande.jpg",
    "rating": "4.9",
    "reviews": 393,
    "category": "LEGO & Lắp ráp",
    "categoryId": "2",
    "brand": "ToyBrands",
    "age": "0-3 tuổi",
    "stock": 87,
    "isNew": true,
    "isSale": false,
    "description": "Sản phẩm Thú nhồi bông Lắp Đáng Yêu 50 mang lại niềm vui bất tận cho bé. Thiết kế an toàn, chất liệu cao cấp."
  }
];

export const BANNERS = [
  {
    "id": 1,
    "title": "Khám Phá Thế Giới",
    "subtitle": "Đồ Chơi Tuyệt Vời",
    "desc": "Nơi mang đến những món đồ chơi giáo dục, mô hình lắp ráp giúp kích thích sự sáng tạo của bé.",
    "image": "https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=1200&q=80",
    "color": "from-blue-600 to-purple-600"
  },
  {
    "id": 2,
    "title": "Sale Mùa Hè Lên Đến",
    "subtitle": "50% Off",
    "desc": "Hàng ngàn sản phẩm đang được giảm giá cực sốc. Đừng bỏ lỡ cơ hội mua sắm thả ga!",
    "image": "https://images.unsplash.com/photo-1585366119957-e9730b6d0f60?w=1200&q=80",
    "color": "from-orange-500 to-red-600"
  },
  {
    "id": 3,
    "title": "LEGO Bộ Sưu Tập Mới",
    "subtitle": "Vũ Trụ Vô Tận",
    "desc": "Những bộ LEGO không gian đỉnh cao vừa cập bến. Số lượng có hạn!",
    "image": "https://images.unsplash.com/photo-1599623560574-39d485900c95?w=1200&q=80",
    "color": "from-slate-800 to-black"
  }
];
